### ISSUE TITLE
Move visualization type determination from render-time to index-time.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#123]
The CCF folks would like to know when a particular dataset is visualizable, and what kind of visualization it has. Currently, this this is done on the front-end by scanning the list of files and looking for recognized file types. This logic could be moved to render time... Right now I don't think the entity index used by the CCF has any mappings... They could either have a new index with mappings, or they could use the portal index.

@ilan-gold : Moving to index-time doesn't feel like we'd be giving up too much flexibility, does it? Is the output just a single type, or is it a more complex structure?

@bherr2 : Please confirm that this would be really useful to you. Not a big chore, I don't think, but unless you were using it, it would be gratuitous.

**Comment by ilan-gold** [comment]
I think this is a broader issue that this ties into nicely.  I don't have a good sense of what goes into it but this feels like the same issue we have with re-running datasets for the purpose of visualization.  I think this would help that because we could just reindex new files.  I like the idea of adding a flag but I don't know what that would look like in practice.

**Comment by bherr2** [comment]
It would definitely be useful for us and would reduce the amount of custom code we have to do to determine if/where to send someone to a visualization from the CCF EUI interface.

**Comment by ilan-gold** [comment]
A different option would be for you to maintain a list of assay types @bherr2 - I think I was a little misplaced in the conversation.  We do check for `files` in the ES response first, but then we have a check on the assays.  This might be best.

**Comment by bherr2** [comment]
A list of assay types would work too, but would not be as automatic. If there is a place in the code where you do the same and I can follow along, that'd work short term.

**Comment by ilan-gold** [comment]
For now, this is our list.

https://github.com/hubmapconsortium/portal-ui/blob/c01ada674ac02d282e3577b82e90a62ad7bffd11/context/app/api/vitessce.py#L82-L94

**Comment by mccalluc** [comment]
@ilan-gold : Looking through the code, I don't feel right now that moving this to index time would be helpful, since it seems to be based primarily just on the assay type... So I'll close this, but reopen if I'm wrong?

On the other hand, there is a problem with the logic:
> ```
>         # Can there be more than one of these?  This seems like a fine default for now.
>        self.assay_type = entity["data_types"][0]
> ```

There can be more than one: We will be seeing `image_pyramid` in addition to other codes, so I'll open a new issue for that.
