### ISSUE TITLE
QUESTION: Where are the organ abbreviations?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#14]
```
GET entities/_search?format=yaml
{
 "size":"0",
 "aggs" : {
  "my-aggregation" : {
   "terms" : { "field" : "organ.keyword" }
   }
 }
}
```
```
    - key: "LK"
      doc_count: 24
    - key: "RK"
      doc_count: 16
    - key: "SP"
      doc_count: 9
   - key: "LV"
      doc_count: 8
    - key: ""
      doc_count: 7
    - key: "LY01"
      doc_count: 5
    - key: "LY02"
      doc_count: 4
...
```
I have some good guesses, but is there a table of these abbreviations?

**Comment by etlds** [comment]
BL: "Bladder",
  BR: "Brain",
  LB: "Bronchus (Left)",
  RB: "Bronchus (Right)",
  HT: "Heart",
  LK: "Kidney (Left)",
  RK: "Kidney (Right)",
  LI: "Large Intestine",
  LV: "Liver",
  LL: "Lung (Left)",
  RL: "Lung (Right)",
  LY01: "Lymph Node 01",
  LY02: "Lymph Node 02",
  LY03: "Lymph Node 03",
  LY04: "Lymph Node 04",
  LY05: "Lymph Node 05",
  LY06: "Lymph Node 06",
  LY07: "Lymph Node 07",
  LY08: "Lymph Node 08",
  LY09: "Lymph Node 09",
  LY10: "Lymph Node 10",
  LY11: "Lymph Node 11",
  LY12: "Lymph Node 12",
  LY13: "Lymph Node 13",
  LY14: "Lymph Node 14",
  LY15: "Lymph Node 15",
  LY16: "Lymph Node 16",
  LY17: "Lymph Node 17",
  LY18: "Lymph Node 18",
  LY19: "Lymph Node 19",
  LY20: "Lymph Node 20",
  SI: "Small Intestine",
  SP: "Spleen",
  TH: "Thymus",
  TR: "Trachea",
  UR: "Ureter",
  OT: "Other"

**Comment by etlds** [comment]
I pull this from the UI constants file

**Comment by mccalluc** [comment]
> I pull this from the UI constants file.

Can you give me a url? Or, better, is there a package I should reference? 

> LY01: "Lymph Node 01",

Is this biologically meaningful name in some community, or just something internal?

**Comment by etlds** [comment]
@mccalluc 
https://github.com/hubmapconsortium/ingest-ui/blob/master/src/ingest-ui/src/constants.jsx

**Comment by mccalluc** [comment]
I've got this working on the front-end. Going to file a new issue for the question about the meaning of the Lymph Node codes, and close this.
