### ISSUE TITLE
ES docs should have nested structure; not flat

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#15]
It’s important that the ES documents for Assays include the full Sample and Donor information, and not just an ID. (and Samples should have Donor information, etc.) We want to be able to facet Assays by characteristics of the Donor.

What should the ES documents look like? I’d suggest a structure like this:
```
{
  "uuid": "....",
  ... # Small number of fields pulled to top.
  "donor": {
    ...
  },
  "sample": {
    ...
  },
  "assay": {
    ...
  }
}
```
Example of something similar from ES docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html

In the ES instance I have right now, it’s pretty flat, and I hope that can change.
- The nested structure preserves information up the provenance chain, without having to rename fields to avoid name collisions.
- The nested structure will be much more tractable to validate with a JSON schema. (Trying to add properties at the same level to emulate a type-sub-type hierarchy won’t work.)

**Comment by shirey** [comment]
@mccalluc Let's discuss this after a standup.  I'm not seeing it- the example you're showing looks pretty flat to me.  The existing structure with ancestors and children being stored in arrays under the entity, I think, provide more flexibility in querying.

**Comment by mccalluc** [comment]
Ok, here's an example: Imagine I'm browsing assays, and want to filter by assay type. Taking [one document](https://portal.test.hubmapconsortium.org/browse/dataset/b9824e6d57a2e861fb990b7a27ba7008) the relevant parts look like:
```json
{
  "ancestors": [
    {
      "entitytype": "Dataset",
      "provenance_create_timestamp": 1577800675845,
    },
    {
      "entitytype": "Sample",
      "provenance_create_timestamp": 1577438435996,
      "specimen_type_display_name": "PFA Fixed frozen OCT block",
    },
    {
      "entitytype": "Sample",
      "provenance_create_timestamp": 1576877329868,
      "specimen_type_display_name": "Organ Piece",
    },
    {
      "entitytype": "Sample",
      "provenance_create_timestamp": 1576877298213,
      "specimen_type_display_name": "organ",
    },
    {
      "entitytype": "Donor",
      "provenance_create_timestamp": 1576875422762,
    }
  ],
  "name": "W105 spleen, anterior seqFISH processed data",
  "uuid": "b9824e6d57a2e861fb990b7a27ba7008"
}

With a data structure like this, how would I:
- Facet datasets by the specimen type they are immediately derived from? I want a list of terms like "PFA Fixed frozen OCT block", but those are going to be dominated by "Organ Piece" and "organ"
- Filter datasets by some inequality on the timestamp of the specimen they were derived from?

I'm not sure these stories are absolutely impossible, but at the least it's going to take some work to make the queries, and I may need to get specific indexes applied.

**Comment by mccalluc** [comment]
(Bill and I talked: He understands the usecase... I'm going to try to use the existing structure, and if that doesn't work, I'll loop back.)

**Comment by mccalluc** [comment]
@shirey : I don't believe anything but dot-path-based access is possible...

[Arrays](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html#array)
> Arrays of objects do not work as you would expect: you cannot query each object independently of the other objects in the array. 

[dot notation](https://www.elastic.co/guide/en/elasticsearch/reference/current/properties.html#_dot_notation)
> Inner fields can be referred to in queries, aggregations, etc., using dot notation

[How arrays of objects are flattened](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html#_how_arrays_of_objects_are_flattened)
> Arrays of inner object fields do not work the way you may expect. Lucene has no concept of inner objects, so Elasticsearch flattens object hierarchies into a simple list of field names and values.

I've looked at `nested` fields, but I don't think that would help here, either.

Here's what I'd propose as the document structure:
- All of this is under the new `metadata` element, which will separate your machine generated fields from those which originate in a TSV (for assays).
- I would propose that there be no scalar fields at the top level of `metadata`: The children should all be objects.
- For Donors:
```
{"metadata": {
  "donor": { ... } }
```
- for Samples:
```
{"metadata": {
  "donor": { ... },
  "origin_sample": { ... },
  "sample": { ... } }
```
where `sample` is the metadata for the object itself, and `origin_sample` is the metadata for the first sample in the provenance chain, typically an organ. If this _is_ the first sample in the provenance chain, `origin_sample` and `sample` will be equal.
- for Datasets:
```
{"metadata": {
  "donor": { ... },
  "origin_sample": { ... },
  "sample": { ... },
  "dataset": { ... } }
```

The complete provenance chain will not be in the ES document: When we need the provenance, we will use the provenance API. I'll loop in people on our side to confirm this plan.

**Comment by shirey** [comment]
@mccalluc This makes sense.  Why not put these new fields at the top level of the object rather than under the "metadata" field, though?  They won't clash with anything we have now.

**Comment by shirey** [comment]
Final decision based on a call with the entire team is this structure:

DONOR-
{
  ....
  "metadata": {....}
}

SAMPLE-
{
  ....
  "portal_metadata_files": 
  "metadata": {....},
  "donor": {
      ....
      "metadata": {....}
   },
   "origin_sample": {

       ....
       "metadata": {....}
   } 
}

DATASET-
{
   .....
  "metadata": {....},
  "donor": {
      "metadata": {....}
   },
   "origin_sample": {
       "metadata": {....}
   }
   "source_sample":[ {
       "metadata": {....}}, {...}, .. ]
   }
}

**Comment by mccalluc** [comment]
This has been implemented, and we're using it.
