### ISSUE TITLE
Published datasets should go to public indices

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#152]
For Datasets, instead of testing for data_access_level == 'public', use status == 'Published' to decide which datasets are added to the public indices (hm_public_*).

This needs to happen because even though the data may be protected (dataset would have data_access_level == 'protected") the metadata stored in the dataset object is allowed to be seen by the public as long as it is published.

**Comment by shirey** [comment]
@etlds @yuanzhou Thinking about this, eventually we should rename the hm_public_* indices to hm_published_*, because that is really what we mean here.  For now leave them as hm_public_*, though, because the UI uses them with the 'public' name.

**Comment by yuanzhou** [comment]
@shirey In search-api, that’ll be just a configuration change once @etlds renames that index.
