### ISSUE TITLE
Entity type "Dataset" should probably be "Assay"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#16]
Here are the entitytypes in the ES I have access to:
```
    - key: "Sample"
      doc_count: 2462
    - key: "Dataset"
      doc_count: 173
    - key: "Donor"
      doc_count: 76
```
```
curl -XGET "http://localhost:9200/entities/_search?format=yaml" -H 'Content-Type: application/json' -d'
{
 "size":"0",
 "aggs" : {
  "my-aggregation" : {
   "terms" : { "field" : "entitytype.keyword" }
   }
 }
}'
```
I suspect `Dataset` is what we at Harvard are calling `Assay`.

@ngehlenborg : I think the concept of Dataset matters to you, and this isn't what you have in mind? Is it important to change this, or could it be left as is?

**Comment by etlds** [comment]
@cborromeo @shirey We need to talk about this either make changes in the neo4j or the script.

**Comment by shirey** [comment]
@mccalluc Dataset is a more generic term.  A dataset may not always point to data generated from a single assay- for example a dataset that is derived from other, multiple datasets.  It also allows for multiple assays to be part of one dataset (not that we particularly want to do that, but we can if we would ever need to)

@etlds FYI

**Comment by mccalluc** [comment]
That works for me; If we do add 'Assay' to ES, give me a heads up? Thanks.
