### ISSUE TITLE
map group_name field in ES from provenance_group_uuid field

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#161]
Currently the group_name field in ES (for all indices) is mapped as a the direct value from the Neo4j Metadata.provenance_group_name field.  Instead, use the Neo4j Metadata.provenance_group_uuid field to look up the displayname field in the [Globus groups json file](https://github.com/hubmapconsortium/commons/blob/master/hubmap_commons/hubmap-globus-groups.json) in hubmap_commons and store the displayname field in all ES  indices.

**Comment by etlds** [comment]
@shirey But what I see in the group_name field in ES are all displaynames. They are all separated by white space, not dash.

**Comment by shirey** [comment]
@etlds These are the current values in PROD.  I think we need to fix that as I've specified above.  It seems like a simple fix that will be resilient to multiple formats of names being stored in Neo4j, which we've had an issue with over time.
![image](https://user-images.githubusercontent.com/5816400/91226796-815cb780-e6f3-11ea-8c32-0e3be82b9e11.png)
