### ISSUE TITLE
Allow users without read access to at least see entry?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#17]
My understanding is that the the provided user token will add a filter to the search, and they will just not see the things they don't have access to. I'm not sure this is quite correct: If a collaborator is looking at an item, and sends me the URL, but I don't have access, I shouldn't get a 404, I should get a 403, with appropriate treatment in the UI: We need to get something back from ES, just to know that the item exists.

If my understanding is incorrect, and this is under control, great! If it does need work, there is a security model in ES, that [distinguishes between document and fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/field-and-document-access-control.html).

**Comment by etlds** [comment]
@yuanzhou Are you returning 403 if the access is not permitted?

**Comment by mccalluc** [comment]
Yes, I would like to. Right now I am only using 403 if `nexus_token` is not in session.

**Comment by yuanzhou** [comment]
Actually this is not what the code does currently. 
- if an access token provided, will check the token validity, invalid token will only get results that are marked as "open" access group. Valid token with read group access will be passed through as it.
- if no token provided, still only return "open" records.

**Comment by yuanzhou** [comment]
So the search api doesn't return neither 401 nor 403. Once we put the search API behind gateway, gateway will allow access to the search api endpoint without checking the token at all. And it only returns 401 if an incorrect search api URL used.

**Comment by mccalluc** [comment]
Relevant issue:  #30. Currently getting 500 if nexus token is missing.

**Comment by mccalluc** [comment]
A world readable Elasticsearch has been set up. Closing.
