### ISSUE TITLE
Tighten access to AWS Elasticsearch Service

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/search-api#2]
At the moment, anyone coming from a Pitt or PSC IP address can read and write the hubmap-es-dev2 ES service.  User-specific access restrictions have to be added.

**Comment by pdblood** [comment]
@shirey @jswelling: Is this issue still relevant?

**Comment by shirey** [comment]
@pdblood this is still relevant.  @jswelling and I should discuss.

**Comment by khanshawPSC** [comment]
@shirey if this is not relevant anymore, close it.

**Comment by shirey** [comment]
This is now controlled with a much tighter firewall list.  Closing.
