### ISSUE TITLE
Can we use UUID as _id?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#23]
Can we use the UUID as the Elasticsearch _id? I believe that when accessing documents, we want to do it with the UUID. To use the UUID right now, the underlying query is 
```
GET /_search
{
    "query": {
        "match" : {
            "uuid" : {
                "query" : "87ba429bd4e38248a40467395478f512"
            }
        }
    }
}
```
... and that particular UUID has four matches. :(

I would prefer to just do:
```
GET entities/_doc/uaIAX3ABUvkh_9SdDx8S
```
which returns a single document.

For the time being, I will use the concise `_id` query rather than the long `uuid` query... I hope that in the future the `_id` will be the `uuid`

**Comment by shirey** [comment]
Use the Entity UUID for the Elastic search _id field instead of the autogenerated value.

**Comment by etlds** [comment]
@mccalluc @yuanzhou _id is a meta field of elasticsearch which is not easy to put custom data in it. We may design the search-api that allow entitties/<uuid>.
Chuck, when I search by the uuid 87ba429bd4e38248a40467395478f512 in Kibana, it only returns one document. Can you send me the id or uuid of the documents you see?

**Comment by mccalluc** [comment]
> _id is a meta field of elasticsearch which is not easy to put custom data in

I may be missing something, but from the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html) I've looked at, specifying the `_id` does not seem at all esoteric.

> Can you send me the id or uuid of the documents you see?

That was on the AWS instance, so it's possible there are no duplicates now, but my concern remains.

**Comment by etlds** [comment]
Thank you, Chuck! I kept looking to put the _id in the document. I neglected the POST <index>/_doct/<uuid> API.
