### ISSUE TITLE
ES: next and previous version attributes

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#233]

**Comment by shirey** [comment]
Map the Dataset.next_revision and Dataset.previous_revision attributes into Elasticsearch for both hm_consortium_entities and hm_public_entities indices.

@yuanzhou Talking to Jonathan he would prefer we use the term "revision" vs "version" for these attributes.

@mccalluc FYI, name change from previous_version and next_version to previous_revision and next_revision.

**Comment by yuanzhou** [comment]
@mccalluc in both entity-api and search-api, you'll see the actual attributes named `next_revision_uuid` and `previous_revision_uuid` since they are the UUID strings.
