### ISSUE TITLE
Pull asset list for derived datasets into parent + flag child to remove from search results

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#235]
cc @ilan-gold 

Users have trouble finding what they really want because they get confused between the parent and child datasets. Proposal:
- At index time, for parents, pull in the assets list for child, under a new attribute. (Want to keep parent and child files separate in UI: probably will not list child files.)
- for children, add a flag so they can be hidden in search results.
- children still accessible by URL, but we will avoid making direct links in UI.

Questions:
- Are we confident there will only be one child, and no grandchildren?
- This only deals with datasets, or are we interested in pulling dataset assets into samples?

**Comment by ilan-gold** [comment]
I think one thing is that we only want to hide certain children, like IMAGE_PYRAMID but not those like SPRM + CYTOKIT or SALMON
