### ISSUE TITLE
Unpublished Donors missing mapped_metadata

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#236]
We noticed a bug in the UI (https://github.com/hubmapconsortium/portal-ui/issues/1549): Some unpublished donors are missing demographic data. Login (or else you'll get a 404) and visit:
- [html has client side error, which we're fixing](https://portal.hubmapconsortium.org/browse/donor/7b12f4f595083d2cba794e78e5c929f1)
- [json works: missing`mapped_metadata`](https://portal.hubmapconsortium.org/browse/donor/7b12f4f595083d2cba794e78e5c929f1.json)

For now we'll handle the data that we have... but should these Donors missing sex/race/age not have made it into the database in the first place? Or it's possible there's a problem with the portal indexing code? 

If these are correct, and may even be published, we should do more UI work to accommodate them.

**Comment by shirey** [comment]
For the donor referenced by both of those links currently there is no donor metadata.  This is the case for many donors in the system.  I think all published donors have a minimum of sex, race, age and bmi attributes, but I'm not sure if all published donors will have this metadata (this is more of a policy question).  Given that we're talking about ingesting data from other consortia where we may not have donor metadata it does seem likely that we will eventually have published donors without this information.

**Comment by mccalluc** [comment]
Thanks! That's everything I needed to know.
