### ISSUE TITLE
Add display_sub_type to ES

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#239]
For DataSubmission, Dataset, Donor and Sample objects:

add a calculated (not stored in Neo4j) field called *display_subtype* to all Elasticsearch documents of the above types with the following rules:
 - Dataset:  the display names linked to the values in data_types as a comma separated list
 - Donor: "Donor"
 - Sample: if specimen_type == 'organ' the display name linked to the value of the organ field otherwise the display name linked to the value of the specimen_type

**Comment by yuanzhou** [comment]
What would be the `display_subtype` for Submission?

**Comment by shirey** [comment]
@yuanzhou Just make it "Data Submission" for all submissions.
