### ISSUE TITLE
Add generic "Intestines" organ? Or make it multivalued?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#241]
@cebriggs7135 writes:
> Tuhin (D. Cotter’s group) explains that each CODEX dataset is comprised of images of slices from 4 different parts of the organ, intestine in this case. So I guess we need an organ ID to indicate both LI & SI.

It wouldn't be hard to [add a new code to the list](https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/organ_types.yaml) ... but I'm not sure that's the right thing to do.

**Comment by shirey** [comment]
@mccalluc We already have those codes, they're in the file that you link to above and in the released master branch.

**Comment by mccalluc** [comment]
chris writes:
> OK, Daniel says it's 4 different parts of small intestine OR 4 different parts of large intestine. Not LI plus SI combined. 

Sorry for the misunderstanding. Closing.
