### ISSUE TITLE
Add submission_id and hubmap_id to ES

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#251]
Add the fields hubmap_id (All entities) and submission_id (Donors and Samples) to ES.  Leave the existing hubmap_display_id and display_doi attributes in place now.  We will deprecate these existing attributes and remove once others dependent on them have switched to the new attributes.

![image (1)](https://user-images.githubusercontent.com/5816400/110945220-6bb78400-830b-11eb-8e1c-f8b8190ec80c.png)

**Comment by yuanzhou** [comment]
Tested on DEV, moving to TEST

**Comment by yuanzhou** [comment]
Related to this issue:
>What other fields are mapped between Neo4j and elasticsearch right now that we should change the name in elasticsearch so all attribute names are the same between Neo4j and ES?

| Neo4j Property  | ES attribute |
| ------------- | ------------- |
| Entity.created_timestamp  | create_timestamp  |
| Donor.label  | lab_name  |
|  (Sample\|Donor).image_file_metadata | portal_uploaded_image_files |
| Sample.lab_tissue_sample_id  |  lab_tissue_id (not found) |
| Sample.lab_tissue_sample_id  |  lab_tissue_sample_id  |
| Dataset.ingest_metadata|  metadata |
| (Sample\|Donor).metadata|  metadata |
| specimen_metadata (not found) |  metadata |
