### ISSUE TITLE
next_revision_uuid not in Elasticsearch

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#259]
Created Datasets via POST on DEV in entity_api, for dataset with uuid = d170b1d22f4efe01decf21cd71171ab6 the next_revision_uuid attribute is not in Elasticsearch.

The previous revision dataset uuid = 5bacc92735b81a2c2cfa94a38fa87b61 and the next revision dataset uuid = 6699f471d83389f0ec02275696a86dfb

**Comment by yuanzhou** [comment]
Addressed via PR https://github.com/hubmapconsortium/search-api/pull/260
