### ISSUE TITLE
Add GET and POST  `/<index>/search` to handle index in search-api

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#31]
ES handles these:
````
GET /<index>/_search
POST /<index>/_search
````
The Search API should require an index to be specified.  The <index> name needs to be modified to hit the Elasticsearch index with the name <access-level>_<index> where access-level is the user's highest level of access (consortium or public), no token being public access.

Additionally because we'll add more indexes in the future create a new call for 
GET /indices that returns a list of valid indices for the search-api (each index for search-api will contain two indices in ES).

**Comment by shirey** [comment]
@yuanzhou As part of this fix can we also add the ability to generally pass any URL arguments (like _search/?pretty) to ES?

**Comment by yuanzhou** [comment]
@shirey sorry I missed your message on the URL arguments. We should be able to handle that in search-api easily.
