### ISSUE TITLE
Support flexible JSON body in search-api requests

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#32]
Currently the search-api looks for this structure in the request JSON:

````
"query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "match_all": {}
        }
      ],
      "should": [],
      "must_not": []
    }
  }
````

Queries like below should be supported:

````
{ "query": { "match": { "display_doi": { "query": "HBM762.FHCT.952", "type": "phrase" } } } }
````

**Comment by shirey** [comment]
@yuanzhou Let's discuss this before you implement.  There may be a more general, but slightly less performing, way of handling this.

**Comment by shirey** [comment]
Closing because we handle these requests consortium/public info split differently now.
