### ISSUE TITLE
`organ_donor_data` or `living_donor_data`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#321]
Bill and I both think it would be better to have this distinction _inside_, rather than in the attribute name, but for now, this is the structure we have.

**Comment by mccalluc** [comment]
Probably fixed, but want to confirm with an example in the index... @yuanzhou , can you copy https://portal.hubmapconsortium.org/browse/donor/3432d3713adbbb51f52973d137a0d7ed from PROD, or provide another example on TEST that has `metadata.living_donor_data`?

**Comment by yuanzhou** [comment]
I had a PROD copy on STAGE last week, and I could see the `metadata.living_donor_data`: https://portal.stage.hubmapconsortium.org/browse/donor/3432d3713adbbb51f52973d137a0d7ed.json

I'll need to check with Bill and see if we should copy the PROD data to TEST in case he or others have testing data there.

**Comment by mccalluc** [comment]
Sorry that I didn’t follow up!

As you note, https://portal.stage.hubmapconsortium.org/browse/donor/3432d3713adbbb51f52973d137a0d7ed.json has `metadata.living_donor_data`

… but there still isn’t metadata in the UI… compare https://portal.stage.hubmapconsortium.org/browse/donor/3432d3713adbbb51f52973d137a0d7ed with https://portal.stage.hubmapconsortium.org/browse/donor/95a62662006235867084078a1e10bebf

… but nothing seems to be more broken than it was before, either. If you’re under any pressure at all, I’d say good to redeploy… but I still need to figure out why it didn’t work, and give you a fix.

**Comment by yuanzhou** [comment]
Merged the latest `test-release` code that contains the fix https://github.com/hubmapconsortium/search-api/pull/325 into the `master` branch and redeployed on STAGE, did a full reindex too. Please verify and let me know if I should go ahead and release the search-api to PROD.

**Comment by mccalluc** [comment]
From slack:

> [Here are three examples](https://portal.stage.hubmapconsortium.org/dev-search?is_living_donor=true) … and clicking through, the metadata shows for each of them. Great! Thanks!

So the code is good, and the reindex will happen soon. Closing.
