### ISSUE TITLE
Graceful transition to nested `metadata`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#33]
I'm on board with the idea of moving towards a nested `metadata` element. I can think of two distinct ways this could be done so we can migrate the portal-ui code.
- For a period, two different ES instances will be available, one with everything at the top level, one with the relevant bits moved into `metadata`
- For a period, the ES instance will have both the top-level and the nested `metadata`.

I don't have a strong preference, but it would be good to be clear about what the path is.

**Comment by shirey** [comment]
@mccalluc Are you talking about the new ingest_metadata field on the Dataset entity?

**Comment by mccalluc** [comment]
I think so? You had mentioned the problem of the top-level space getting cluttered, and names starting to collide, and we all agreed our metadata could be down a level. Here, I'm just trying to get clear on what that path is. Thanks!

**Comment by mccalluc** [comment]
This migration has happened. Moot.
