### ISSUE TITLE
List supported fields

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#35]
In order to make the UI, I need to know that some fields are present in a reliable location in the response documents. If they aren't, a schema validation error can be very useful by pointing directly to the problem, instead of only knowing that the screen doesn't look right.

Way back when, I had tried to infer a schema from the Entities. It was never very good, and now every page has tons of warnings.

Do you think you all would be able to commit to any schema for ES documents? At the very end of the pipeline, if I got a response that failed validation, we could all agree that that there is a bug. Perhaps you would also use it earlier in the index pipeline... but that's an implementation decision for you.

- Do you agree that some schema is necessary for me to construct a UI, at for some core fields?
- I'd be glad to author, if you can provide information about what is really stable.
- Or if can author and provide to me, I can work with that.

**Comment by shirey** [comment]
If you want to construct the schema we can provide a list of fields that will be available by top level entity type with those that will always be there tagged as such (not all fields can be guaranteed to be filled in, of course).

**Comment by mccalluc** [comment]
Yes, that would be great. As the metadata from ingest-validation-tools starts to filter through, I'll know what to expect in those structures, too. Thanks!

**Comment by shirey** [comment]
Create a list, in a spreadsheet, of all current fields by entity type (Donor, Sample, Dataset) as exposed from Elasticsearch.  Include columns for Entity Type, full field path (e.g. donor.uuid, dataset.ingest_metadata.data_type) and required field (i.e. will a value always exist).

Include separate lists of allowable values for fields that have them, such as organ and data_type.

**Comment by shirey** [comment]
@mccalluc Here is a draft of the fields in Elasticsearch.  These aren't currently being exposed this way, but will be soon.  Of note the "files" attribute moved out of the ingest_metadata field to the top level of the document (and ingest_metadata is now just metadata as discussed earlier this week).  https://docs.google.com/spreadsheets/d/1L8mfs767Z5ZGnZ92UJySlHxprraSariH1dU45g6jphE/edit?usp=sharing
