### ISSUE TITLE
Include CCF RUI data in sample metadata

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/search-api#36]
The RUI data is provided during ingestion and is in JSON format. Ideally it's included as is in the metadata where appropriate.

I can potentially provide the JSON Schema for the CCF v0.5.0 data if needed.

@shirey is aware. Let me know if anything is needed and when it can be made available. Our CCF Sprint starts on Monday. It doesn't _have_ to be in there right this instance, but would need it before our _next_ Sprint which starts in May.

**Comment by shirey** [comment]
@bherr2 Closing, I think this is long done..sorry for loosing track.  If there is still a problem please reopen and tag me.
