### ISSUE TITLE
Include metadata for CCF EUI

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/search-api#37]
For the EUI, we will need some metadata. I realize some may not be possible to get at this time, but I wanted to get this on people's radar. Hopefully some/most of these can be addressed by May.

Donor:
* Age (at time of death)
* Sex (Male/Female/Other)
* BMI

Sample:
* RUI JSON Data

Data Set (is this where Tissue Images will come in?):
* TMC (maybe this is in Sample or Donor?)
* Technology (IMS, MxIF, PAS)
* Processed TIFF URLs (for giving to the vitessce image viewer)

We could use more/other data, but this would be a minimum set based on our current [plans](https://xd.adobe.com/view/87cdc0cf-77ca-4c15-74a0-3db0b0e2f6af-f1fc/).

**Comment by shirey** [comment]
@bherr2 Another lost issue.  Closing now, but feel free to reopen and tag me if something needs to be done yet.
