### ISSUE TITLE
500 if expired token presented?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#39]
You should be able to find an error in the log a little after 2020-04-20 10:10pm: I guess that the nexus token I provided was expired, and this produced a 500... Should have been 401? (I don't know if there's a way to force expire tokens? If there were, I might be able to reproduce.)

**Comment by yuanzhou** [comment]
In the new deployment, if your globus token is expired, you'll still be able to query but only get back public accessible results.

**Comment by bherr2** [comment]
@yuanzhou does this mean unauthenticated users can see the public results now? I know that's the plan eventually, but is that what you mean here?

**Comment by yuanzhou** [comment]
@bherr2 it's no longer that case. I'll roll out an update to the search-api fairly soon, it will require all calls to have the valid globus token. There are 3 cases:


**Case 1: Missing/invalid/expired token**
If a token is missing, invalid or expired, an error message with 401 status code will be returned.

**Case 2: Valid token without the right group access**
In the case that the token is valid BUT the owner of this token doesn't have the right group access, a 403 error message will be returned.

**Case 3: Valid token with right group access**
With a valid token (that represents a user who has the correct group access to the indexed data), ALL the user specified search query DSL (Domain Specific Language) detail will be passed to the Elasticsearch just like making queries against the Elasticsearch directly, and the search hits results will be returned. Elasticsearch will also return any error messges if the JSON query is misformatted.

**Comment by yuanzhou** [comment]
Addressed with the new deployment of search-api on DEV and TEST
