### ISSUE TITLE
When casting to int, what if we have an array?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#428]
https://github.com/hubmapconsortium/search-api/blob/436ae967c54cf3e4084f952f5ca78ebc78376e75/src/elasticsearch/addl_index_transformations/portal/__init__.py#L238

```
  File "./elasticsearch/addl_index_transformations/portal/__init__.py", line 238, in _simple_clean
    as_number = int(v)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

Look more closely at the examples which failed... we're expecting a number at this point in the metadata, so what went wrong?

Cases to consider:
- `["1.234"]`?
- `["1", "2"]`?
- `[1, 2]`?
- `["not a number"]`?

Log in to see five failing examples: https://portal.test.hubmapconsortium.org/dev-search?index_version[0]=2.2.1

**Comment by yuanzhou** [comment]
Turned out that the pipeline is causing this issue. The call `https://entity-api.test.hubmapconsortium.org/entities/b57f7458986473e4fa57fd418ec9f894` returns `ingest_metadata.metadata.null` field, and this is from the pipeline result I believe.

From @jswelling 
>Maybe two tabs in a row in the metadata.tsv file? I’ll track it back when I return on Monday but I don’t see how that could get past ingest-validation-tools.
