### ISSUE TITLE
Chech Azimuth zarr files at index time

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#445]
Apply the logic from https://github.com/hubmapconsortium/portal-ui/pull/2313 here in this repo. Possible problems:
- SSL slowness is unlikely to go away. Will waiting for slow network requests at index-time be a problem?
- In the environment provide a groups token so that that on the unpublished index, unpublished files can be accessed? If not, we won't be able to properly visualize them.
- Additional dependencies: 
```
aiohttp==3.8.1
fsspec==2021.11.1
zarr==2.10.3
```

@yuanzhou -- Will any of these be insurmountable?

**Comment by yuanzhou** [comment]
@mccalluc Bill mentioned that we won't be doing the file check at index time due to some of his concerns. I'm not sure if this is that related issue, can you confirm?
