### ISSUE TITLE
Search-api: API_TYPE only allows selection of two options

### ISSUE THREAD

**Issue by davism84** [hubmapconsortium/search-api#468]
Need to support any application. 

causes an error if set to anything else
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from app import app as application
  File "./app.py", line 61, in <module>
    "Required configuration parameter API_TYPE not found in application configuration. Must be set to 'HUBMAP' or 'SENNET'.")
ValueError: Required configuration parameter API_TYPE not found in application configuration. Must be set to 'HUBMAP' or 'SENNET'.

**Comment by davism84** [comment]
maybe this can come from the configuration and use a form of "reflection" to instanciate

**Comment by maxsibilla** [comment]
Issued a new PR to dev-integrate to address this. New app config setting is "TRANSLATOR_CLASS" that will be the name of the translator class the user wants to use
