### ISSUE TITLE
search-api: make public indices optional

### ISSUE THREAD

**Issue by davism84** [hubmapconsortium/search-api#469]
need to make the public index optional to support those apps that don't have a public index, only private

**Comment by maxsibilla** [comment]
This should largely be handled by the application specific translators: https://github.com/hubmapconsortium/search-api/blob/2fd5ae3e927ca4f91f72b4e02f9ba89747a57831/src/translator/bcrf_translator.py#L51

Each translator defines how they expect `search-config.yaml` to be defined so we can add logic to the `bcrf_translator.py` file to handle this or just remove the above line.

**Comment by yuanzhou** [comment]
Closing this issue since it's been over a year and half and we don't seem to have this need or it's not clear if we'll ever need it. Will reopen if necessary.
