### ISSUE TITLE
search-api: add error

### ISSUE THREAD

**Issue by davism84** [hubmapconsortium/search-api#473]
getting the following error upon adding

DEBUG:urllib3.connectionpool:http://es01-test:9200 "PUT /bcrf/_doc/461bbfdc353a2673e3814444665553 HTTP/1.1" 400 188
ERROR:libs.es_writer:Failed to write doc of uuid: 461bbfdc353a2673e3814444665553 to index: bcrf
ERROR:libs.es_writer:Error Message: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}},"status":400}

**Comment by maxsibilla** [comment]
Resolved issue by using `json.dumps` prior to indexing document
