### ISSUE TITLE
Utilize AWS CloudWatch to catch reindex errors

### ISSUE THREAD

**Issue by maxsibilla** [hubmapconsortium/search-api#515]
We should be able to utilize CloudWatch to grep the logs coming from the search-api and send an alert if some form of the following errors appear:

`[2022-06-07 14:47:11] ERROR in es_writer:57: Error Message: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"mapper [descendants.metadata.metadata.library_final_yield] cannot be changed from type [long] to [float]"}],"type":"illegal_argument_exception","reason":"mapper [descendants.metadata.metadata.library_final_yield] cannot be changed from type [long] to [float]"},"status":400}`

`[2022-06-06 18:32:19] ERROR in es_writer:57: Error Message: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"mapper [descendants.metadata.metadata.library_final_yield] cannot be changed from type [float] to [long]"}],"type":"illegal_argument_exception","reason":"mapper [descendants.metadata.metadata.library_final_yield] cannot be changed from type [float] to [long]"},"status":400}`

**Comment by yuanzhou** [comment]
CloudWatch alarms already in place
