### ISSUE TITLE
Documents with multiple mapper version showing up in index

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#528]
Data indexed under three different three index versions is currently on prod. https://portal.hubmapconsortium.org/dev-search
```
2.3.8 8178
2.3.9 6892
2.3.10 2384
```
My understanding was that reindexes were done as a batch, and while you aren’t able to provide atomic updates there should, in any event, never be more than two different versions present.

Do you understand what’s going on here, and how it can be prevented in the future?

Zhou:
> I've been doing live reindex-all after each search-api release on PROD. Maybe there's a bug in the reindex-all call. Let me fix this by doing a full reindex tonight, which deletes the indices first then recreate them. The live reindex-all doesn't erase the indices.

**Comment by yuanzhou** [comment]
Chuck:
>Before you destroy the current state, I suggest you look more carefully at it: Are there any commonalities between the documents that didn’t get re-indexed with the latests mapper?
Looking ahead, could you add a check to the end of the index run that confirms that the job completed?
If you will be wiping the index, I suggest having a plan to role back changes, in case there is a problem, and I’d suggest putting up a message now warning users about the outage.

**Comment by yuanzhou** [comment]
I looked into the issue, turned out that 
- the 2.3.8 release reindex-all failed due to AWS outage
- the 2.3.9 release was for Joel's CODEX2 assay type changes, then he changed again for the 2.3.10 release and I forgot to trigger the reindex-all. 

To fix this issue, I'll do a full reindex which erases the old indices then recreate them.

**Comment by yuanzhou** [comment]
Fixed https://portal.hubmapconsortium.org/dev-search
