### ISSUE TITLE
Endpoint to search just one index?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#57]
On test, it looks like you are experimenting with multiple indexes:
```
curl 'https://search-api.dev.hubmapconsortium.org/search' -H 'Content-Type: application/json;charset=utf-8' -H 'Authorization: Bearer ...' --data '{"_source":{"includes": []}, "query": {"ids": {"values": ["44be1ce06db790c05bc5a1d763420919"]}}}' | python -m json.tool | grep -A1 '"_id"'

                "_id": "44be1ce06db790c05bc5a1d763420919",
                "_index": "entities",
--
                "_id": "44be1ce06db790c05bc5a1d763420919",
                "_index": "hm_consortium_entities",
--
                "_id": "44be1ce06db790c05bc5a1d763420919",
                "_index": "hm_public_entities",
```
This causes problems for us because IDs are no longer unique.
- Is there, or will there be, endpoints which hits only a single index? Out of the box, you could just add the index to the path, but that doesn't seem to work here.
- Or do we need to index constraints to queries on our side? (not a good option)
- Or something else?

Also: Should `_source` work? I might not have the syntax right above, or maybe it's something your wrapper doesn't pass through?

**Comment by shirey** [comment]
We're adding the functionality to hit individual indexes.  https://github.com/hubmapconsortium/search-api/issues/31

**Comment by mccalluc** [comment]
Ok, that will cover this. Closing.
