### ISSUE TITLE
Support for portal indices after `sample_category` addition

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#592]
When `specimen_type` is no longer a required field ensure that he portal mapping/translation code correctly handles `specimen_type` if it is not included in the document.  i.e., make sure it doesn't throw an error and make sure the `mapped_specimen_type` field in the portal indices is not included if `specimen_type` is missing in the main (entities) document.

Additionally, confirm with @john-conroy, and add as needed any additional mapped `sample_category` field for the portal indices.

The new values, as stored in the db, returned from entity-api and stored in the `sample_category` field of the entities indices will be:

```
organ
block
section
suspension
```

**Comment by john-conroy** [comment]
With those values, we shouldn't need any additional mapping so we should be able to just remove the `mapped_specimen_type` translation.
