### ISSUE TITLE
use search-api configured index name for `scroll-search` endpoint

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#609]
For the `/<index>/scroll-search` endpoint instead of taking the actual index name in ES/OpenSearch use the configured name and resolve to the actual private or public index name via the configuration file and the access level of the user token (or lack of token).

**Comment by kburke** [comment]
Pretty simple change.  But for internal use, I did overload this single endpoint so it handles open, read, and delete of a scroll search. Distinguishing the operation requested involves looking at JSON arguments. I want to confirm that is acceptable, Restful, etc.

Additionally, ```<index>``` is ignored for read and delete operations.  Only the ```scroll_id``` of the JSON is used, and I have not looked to see if there is a way to confirm ```scroll_id``` is for ```<index>```.  Is that acceptable for a public endpoint?  If so, should we accept a second endpoint explicitly showing we don't use the index, like:
```
        @self.app.route('/<index>/scroll-search', methods=['POST'])
        @self.app.route('/scroll-search', methods=['POST'])
```
