### ISSUE TITLE
Discontinue use of tissue_sample_types.yaml

### ISSUE THREAD

**Issue by kburke** [hubmapconsortium/search-api#653]
Where a '`display_subtype`' is assigned to an ElasticSearch document for non-organ Samples, discontinue use of the `tissue_sample_types.yaml` file.  Replace with a capitalized of the `sample_category`, which should cover Block, Suspension, and Section.

See also [files-api#43](https://github.com/hubmapconsortium/files-api/issues/43)
See also [search-api#723](https://github.com/hubmapconsortium/search-api/issues/723)

**Comment by kburke** [comment]
https://github.com/dbmi-pitt/search-adaptor/pull/50
https://github.com/hubmapconsortium/search-api/pull/728

**Comment by yuanzhou** [comment]
https://github.com/hubmapconsortium/search-api/issues/723
