### ISSUE TITLE
Remove deprecated fields from OpenSearch and fine tune `index.mapping.total_fields.limit`

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#686]
Based on conversation from https://github.com/hubmapconsortium/search-api/issues/679

**Comment by yuanzhou** [comment]
- Bumped up tp 4000 fields via PR https://github.com/hubmapconsortium/search-api/pull/682
- Removed `source_sample` and `origin_sample` via PR https://github.com/hubmapconsortium/search-api/pull/681
- Removed `specimen_type` and `specimen_type_other` via PR https://github.com/hubmapconsortium/search-api/pull/611

**Comment by yuanzhou** [comment]
Did analysis and comparison with the following findings:
- 101 + 3507 = 3608, meaning 101 fields not get into ES due to max limit fields 3500 setting, however we got 3507 total mapped fields, possibly inaccurate count returned due to latency during the reindex process
- 3608 - 179 = 3429, meaning 179 deprecated fields removed, perfect match with the current 3429 total fields. 
- Keep the new max limit fields at 4000 allows extra room

**Comment by shirey** [comment]
Release pending cleanup from Harvard in the index portal translation.
