### ISSUE TITLE
Rework entity reindexing based on analysis

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#699]
Rework the entity reindexing algorithm based on the outcome of the analysis in #698

**Comment by yuanzhou** [comment]
I'll create a list of smaller tasks as a breakdown of this major effort.

**Comment by yuanzhou** [comment]
Link https://github.com/hubmapconsortium/search-api/issues/744

**Comment by yuanzhou** [comment]
Replaced by https://github.com/hubmapconsortium/search-api/issues/744
