### ISSUE TITLE
File path as key under `other_meta`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#72]
Can you give us some insight into what's going on under `other_meta` here? https://portal.dev.hubmapconsortium.org/browse/dataset/99c90fd778f652b5f0dc4e2f337d4791.json:
```
...
metadata: 
  dag_provenance:  
    scan_and_begin_processing.py: "b594567"
  metadata:  
    collectiontype: "codex"
    components: []
    other_meta:  
      src_data/experiment.json:  
        HandEstain: false
        aperture: 0.75
        backgroundSubtractionMode: "auto"
...
```
Our UI is choking on the "src_data/experiment.json" right now.
- Is this meaningful data that we could expect to see on TEST and PROD, and the UI should handle it?
- Is it old messy data that could be removed from DEV in some timeframe?
- Is it old and messy, but likely to hang around, so the UI probably needs to at least not crash?

**Comment by shirey** [comment]
This data seems relevant to me, but I'm not the right person to say what should be shown or not.  I don't think this is old data- it may be added after a successful pipeline process- @jswelling , do you know if we're still producing this from pipelines, or can it just be removed from dev and we'll be done with it?

**Comment by yuanzhou** [comment]
This specific dataset is no longer available.
