### ISSUE TITLE
Remove the assaytype calls eventually

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#721]
Once all the API consumers finish the switch and use equivalent UBKG ontology-api calls, we'll need to remove the following calls from search-api and search-adaptor as well as API Gateway:

- `POST /assayname`
- `GET /assaytype`
- `GET /assaytype/<name>`

And all the underlying code:
- https://github.com/hubmapconsortium/search-api/blob/main/src/libs/assay_type.py
- https://github.com/hubmapconsortium/search-api/blob/main/src/libs/assay_type_schema.yml

This will happen after https://github.com/hubmapconsortium/commons/issues/114

Also related: https://github.com/hubmapconsortium/search-api/issues/687

**Comment by yuanzhou** [comment]
@maxsibilla we haven't fully addressed this card. Did you close it by accident?

**Comment by maxsibilla** [comment]
@yuanzhou yes must have been an accident
