### ISSUE TITLE
Switch deriving "subtype" for Datasets from `data_types` to `dataset_type`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#723]
Switch from deriving the "subtype" for Datasets using the `data_types` field to the new `dataset_type` field.

See also [search-api#653](https://github.com/hubmapconsortium/search-api/issues/653) to use [organ codes from UBKG](https://ontology.api.hubmapconsortium.org/organs/by-code?application_context=HUBMAP)

**Comment by yuanzhou** [comment]
Also link to the related issue: https://github.com/hubmapconsortium/search-api/issues/653

**Comment by yuanzhou** [comment]
Already addressed via #737

**Comment by shirey** [comment]
Dupe of #737, closing
