### ISSUE TITLE
Analysis: New reindex procedures

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#744]
For both:
  - reindex/index of an entity by id
  - reindex entire database

Without looking at current implementations is it possible to create a standalone service that would be able improve the speed/performance when indexing entities in the following cases:
  - entities that have large numbers of samples or datasets under them like Donors `3a0960c7cc8864dcc003165cef9ca040` or `171fc88db789ff330b0d7a420b642a23`
  - entities that have a large number of datasets associated as direct ancestors (need to create an example in a stand-alone database)- could connect Publication `77ab35880329b5932380104aa58795a4` to all 209 datasets as direct ancestors as intended, instead of the workaround where collection `074df152c7d3dc2e09ec2400e947bc0c` is attached to the publication via a "[:USES_DATA]" relationship, which in turn points to the 209 datasets (publications `3c7273660cdf9ab91a7901533b2cd9a5` and `72cbeb8ff605fd5017cb2666cd19dfb7` are also examples where we need to remove this workaround)

**Comment by yuanzhou** [comment]
What's really taking time during index process is adding all the descendants and ancestors to the document. For example, Donor `3a0960c7cc8864dcc003165cef9ca040` has 24,798 descendants.
<img width="655" alt="Screenshot 2024-02-19 at 4 31 53 PM" src="https://github.com/hubmapconsortium/search-api/assets/195873/e9634f69-193b-45b8-88ca-5d39bd11b492">

And Dataset `925886f2f50e70a639b95cecfaabac25` has 168 ancestors including 72 direct ancestors
<img width="799" alt="Screenshot 2024-02-19 at 9 47 17 PM" src="https://github.com/hubmapconsortium/search-api/assets/195873/cf8d81fa-d589-44ab-a214-c83618735e4f">

And Publication `0de8528cf78f686a3e560c1860ddde63` has 360 ancestors
<img width="580" alt="Screenshot 2024-02-19 at 4 47 17 PM" src="https://github.com/hubmapconsortium/search-api/assets/195873/e34bd7b4-d7f9-4880-b91a-309d4fc7e3c2">

Among these added fields during runtime, do we really need `ancestors` and `descendants`? Does portal-ui really consume them?
```
'donor',
'origin_samples',
'source_samples',
'ancestor_ids',
'descendant_ids',
'ancestors',
'descendants',
'files',
'datasets',
'immediate_ancestors',
'immediate_descendants'
```

**Comment by yuanzhou** [comment]
Index procedure analysis: https://gist.github.com/yuanzhou/09274afe4acfc1ec1ced1caf64e36f8a
