### ISSUE TITLE
Refactor out `display_subtype` logic

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#752]
**AFTER** implementing the logic of generating `display_subtype` using `on_index_trigger` in entity-api via https://github.com/hubmapconsortium/entity-api/issues/631, we'll need to refactor out all the related handling from `hubmap_translator.py`. 

This also involves updating the search-adaptor method `init_translator()` by removing the `ONTOLOGY_API_BASE_URL`: 
https://github.com/dbmi-pitt/search-adaptor/blob/aad2d910674382341145db960170a92a5ddaa6e7/src/app.py#L1260C124-L1260C145

Then test against the corresponding entity-api to ensure this `display_subtype` still gets indexed in AWS OpenSearch.

**Comment by shirey** [comment]
Won't do this, as it will cause unforeseen downstream issues
