### ISSUE TITLE
Improve performance UUID-API get_hubmap_ids

### ISSUE THREAD

**Issue by DerekFurstPitt** [hubmapconsortium/search-api#766]
During a reindex, each call to entity api's get_entity_by_id spends a large amount of time making a call to uuid to retrieve the ids. Add profiling like we did in entity and search api to see if we can find any specific bottlenecks.

Pull out individual queries that are run for the standard GET call, test individually against a copy of the PROD database and see if any performance improvements can be made to the queries or possibly by adding additional indices.

**Comment by yuanzhou** [comment]
<img width="1169" alt="Screenshot 2024-03-13 at 1 19 04 PM" src="https://github.com/hubmapconsortium/search-api/assets/195873/46853ceb-8ca3-479a-83cb-cb2e201476f4">

**Comment by shirey** [comment]
Queries and indexing all looked good when @kburke looked at them.  Closing.
