### ISSUE TITLE
Add EPICollections to indices

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#787]
Add EPICollection (created by [Entity API Issue #669](https://github.com/hubmapconsortium/entity-api/issues/669) ) to the entities consortium level index only (no need to add to public index or portal indices at this time).

**Comment by yuanzhou** [comment]
@shirey @DerekFurstPitt as a result of the recent efficiency work, we'll no longer need to use the mapping json in sesrch-api to control what fields get indexed. Now we can achieve this by using the same entity schema yaml and marking the fields as `indexed: true | false`. For example: https://github.com/hubmapconsortium/entity-api/blob/8ad7ae692d8d72e06d969cf550e2d6efe0321a26/src/schema/provenance_schema.yaml#L244

@kburke implemented this feature and can explain more if @DerekFurstPitt will have questions.
