### ISSUE TITLE
Remove top-level copied field `files`

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#805]
During the index/reindex runtime, the Dataset `ingest_metadata.files` field gets copied to a top-level filed `files`. Recently we've come across some datasets that contain a large number of `ingest_metadata.files` (the Dataset field `ingest_metadata` gets renamed to `metadata` during index runtime) entries (`fbf3af732f53b00f20a9ecc1ecc3c52b` for instance, the payload size 2MB). 

<img width="653" alt="Screenshot 2024-05-22 at 10 54 57 PM" src="https://github.com/hubmapconsortium/search-api/assets/195873/fb01ea6e-1db5-41b8-9cac-d8df0970b636">

Such duplicates have caused:

- bigger response json payload (> 10MB)
- longer search query execution and reindex time

We should remove the original one and only keep the copied version.

**Comment by bherr2** [comment]
We read from metadata.files. Does this affect that? 

PS. Here are the fields we query for / use: https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-database/src/lib/xconsortia/xconsortia-data-import.ts#L17-L38

**Comment by bherr2** [comment]
On `ccf-ui` side, that's correct.

**Comment by yuanzhou** [comment]
@bherr2 @john-conroy if you are sure you don't use the top-level `files` field, we'll plan to remove it, is that fine with you?

There will be additional upcoming changes to the Dataset `metadata.files` and `metadata.metadata` in the near future. We'll discuss and come up with a plan.

**Comment by bherr2** [comment]
Fine by me

**Comment by john-conroy** [comment]
I'll have to look through our repos before I can fully confirm.

**Comment by yuanzhou** [comment]
Closing this issue, will handle this separately.
