### ISSUE TITLE
CLT Manifest Endpoints

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#821]
Currently API users who want to download HuBMAP data need to translate queries to valid Globus endpoint links in order to download the data.  This can be cumbersome if a lot of datasets match a given query.  To assist these users we'll create new endpoints that output a manifest file consumable by the [HuBMAP CLT Tool](https://docs.hubmapconsortium.org/clt/index.html) based on existing query types.

To the existing endpoints `/search`, `/<index-name>/search` and `/param-search/dataset` add the new query argument `produce-clt-manifest`, which when set to `true` (e.g. `/search?produce-clt-manifext=true`) will produce a manifest.txt file which contains the information to download all datasets which match the query in valid CLT mainifest syntax.  To produce the list of datasets, the query result should be filtered (after performing the ES query) to only returned datasets, ignoring other entity types, Donors, Samples, Collections, etc.  If the query succeeds, but no datasets are present in the returned query return a `204`, empty response status.

**Comment by yuanzhou** [comment]
Note: existing issue on PROD, not introduced by this round of updates. 
>/param-search/datasets only returns a maximum of10 results

Will address in a separate card.
