### ISSUE TITLE
Release parameterized search feature

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#822]
The [Parameterized Search feature](https://github.com/dbmi-pitt/search-adaptor/blob/21ce1dc1fe974010b6dd31baf9036babc8891bf4/src/app.py#L148) was released to production a while ago, test to make sure it is working as expected before we announce that it is released after the documentation for it has been updated under the [update param-search documentation issue](https://github.com/hubmapconsortium/documentation/issues/4)

**Comment by kburke** [comment]
Confirmed param-search works as expected.  Past sample searches with explanations to Bill for [documentation/issues/4](https://github.com/hubmapconsortium/documentation/issues/4).
