### ISSUE TITLE
DRY - only call `get_organ_types()` once

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#841]
Currently each call to `generate_display_subtype()` method further calls this `get_organ_types()` against UBKG ontology-api to retrieve the static/fixed organ info. Move `get_organ_types()` to the initialization phase as a one-time data fetch and reuse the result in all the iterations of generating `display_subtype`.

**Comment by kburke** [comment]
@yuanzhou The solution in https://github.com/hubmapconsortium/search-api/pull/845 would currently require a restart of search-api if UBKG were updated with new organs.

Also, a card similar to this should be written for entity-api, which does the same thing in more places.
https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/schema/schema_triggers.py#L1019
https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L3131
https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L3403
https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L3694
https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L3792
https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L5208

**Comment by yuanzhou** [comment]
@kburke thanks for noticing the need of restarting search-api container, the same applies to entity-api when UBKG updates the organs. Normally I handle that during the redeployments.

Yes, the entity-api retrieves the organs from UBKG ontology-api in a similar fashion. It caches the result and normally only individual calls get made. So performance need is not as obvious as in search-api with a lot more requests being made. I'll add a new card to consolidate those calls in entity-api and we can address that later when things slow down a bit. Thanks for pointing that out.

**Comment by kburke** [comment]
I'm not sure of the point of [the /samples/prov-info endpoint](https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L3760C13-L3760C31), but I'm certainly watching its calls to [validate_organ_code()](https://github.com/hubmapconsortium/entity-api/blob/5cd1c77504e12c26b0592b3b088252ceb6a64e09/src/app.py#L3827) call ontology-api repeatedly, seemingly without caching.

Flipping to load on initialization, and using that value everywhere needed should cover that, but maybe we want to double-check usage of cached values in some way?
