### ISSUE TITLE
reindex-all script - "catch-up" the active index

### ISSUE THREAD

**Issue by kburke** [hubmapconsortium/search-api#855]
The `scripts/fresh-indices/fresh-indices.sh` script currently supports a `create` command which creates a new ElasticSearch index with a time-stamped name, and fills it with documents created using _current_ Neo4j data. However, there can be entities whose documents fail to be written to the ES indices, and there can also be create, update, and delete activity on Neo4j entities while the `create` command is executing.

The catch-up command to the  `fresh-indices.sh` script is designed to "re-index" each of these missed entities into the index created during the `create` command.  The current implementation of this command simply prints out UUIDs which need to be re-indexed.

Finish implementation of the `catch-up` command.  The index to write the documents to should be able to be overridden with script arguments.
- By default, use the `op_data` file from the `create` command execution, and re-index into the same `destination` indices as `create`.
- If the `create` indices have been swapped to be the active indices used by `search-api`, accept a command-line argument to re-index into those indices instead.

**Comment by yuanzhou** [comment]
9/30/2024, @shirey FYI:

After going over the updates, @kburke and I agreed to tweak the workflow:
- `create` creates new indices and fills in with all documents. At the end of this operation, it generates a json file that captures all the uuids from failed entity-api calls as well as timestamp info of the last modified documents from old indices.
- `go-live` swaps the indices from the old ones to the new ones in a timely fashion. Then it triggers individual reindex against new indices on the failed entities (if found any) and the ones that have been updated  during the previous step.

This workflow will minimize the service downtime and will also allow automation in the future.
