### ISSUE TITLE
Remove ancetor.* and descendant.* fields that are uneeded

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#857]
For all indices, remove all fields under the `ancestors.`, `descendants.`, `immediate_ancestors.` and `immediate_descendants.` fields EXCEPT for the following:

Needed by IU:
```
  'descendants.entity_type',
  'descendants.ingest_metadata.metadata.tissue_id',
  'descendants.last_modified_timestamp',
  'descendants.group_uuid',
  'descendants.group_name',
  'descendants.created_by_user_displayname',
  'descendants.uuid',
  'descendants.hubmap_id',
  'descendants.dataset_type'
  
  # Zhou added below fields based on conversation between Bruce and Max - 9/5/2024 
  'descendants.thumbnail_file'
  'descendants.submission_id'
```
Needed by Harvard/Portal:
```
ALL.uuid
ALL.entity_type
ALL.last_modified_timestamp
ALL.created_timestamp

Donor.metadata

Sample.organ
Sample.sample_category

Dataset.dataset_type
Dataset.published_timestamp
Dataset.thumbnail_file
```

**Comment by yuanzhou** [comment]
With the [recent updates](https://github.com/hubmapconsortium/search-api/pull/861) made by Harvard team, each object inside `ancestors`, `descendants`, `immediate_ancestors` and `immediate_descendants` will only need to contain `entity_type` for portal indices. FYI @kburke 

<img width="1151" alt="Screenshot 2024-08-30 at 10 19 19 AM" src="https://github.com/user-attachments/assets/806a1afc-734c-4946-95b9-cd485a9e0920">

**Comment by kburke** [comment]
Regarding the previous comment, because there are probably going to be "efficiency opportunities" after I'm creating documents which meet the requirements of this issue, I'm also including "uuid" along with "entity_type" for "ancestors" and "descendants" when generating documents for the portal indices.

This might be eliminated later if not useful, but I think it is a small element to retain in the doc for now.

**Comment by yuanzhou** [comment]
@kburke on the Harvard side, there's no need to include the `uuid`. They just need `entity_type` for the counts. Eventually they'll stop using `ancestors`, `descendants`, `immediate_ancestors`, and `immediate_descendants`. They said they can work with only the ids arrays later.

**Comment by yuanzhou** [comment]
@kburke the IU team did some recent refactoring. After confirming with Bruce, on the HuBMAP side they'll only need `descendants.dataset_type` and `ancestors.rui_location`. Those fields (https://github.com/x-atlas-consortia/hra-api/blob/main/src/library/ds-graph/utils/xconsortia-fetch.js#L9) we handled earlier are only for SenNet now.
