### ISSUE TITLE
Get entity ancestors in order from search-api

### ISSUE THREAD

**Issue by john-conroy** [hubmapconsortium/search-api#86]
The array of `ancestors` in the search-api response is not always in order by provenance. We are currently sorting each ancestor by `create_timestamp`, but this is a tenuous solution. We should determine if it's feasible to receive the `ancestors` array in order.

**Comment by mccalluc** [comment]
(I've pinged Bill on Slack.)

**Comment by shirey** [comment]
@john-conroy We could try this, but..
Two issues
  
1.  Does Elasticsearch guarantee the order of an incoming list when it returns it?
2. It is possible for a child to have more than one parent, so in that case you could end up with multiple in a row that aren’t ancestors/descendants of each other (they belong at the same level, which isn't represented in an ordered list..).

**Comment by yuanzhou** [comment]
No longer relevant after the recent updates to ancestors. descendants, immediate_ancestors, and immediate_descendants.
